attention_head_size: 2
categorical_groups: {}
causal_attention: true
dropout: 0.3
embedding_labels:
  is_ocean:
    land: 0
    ocean: 1
  location_id:
    '0': 0
    '1': 1
    '10': 2
    '100': 3
    '101': 4
    '102': 5
    '103': 6
    '104': 7
    '105': 8
    '106': 9
    '107': 10
    '108': 11
    '109': 12
    '11': 13
    '110': 14
    '111': 15
    '112': 16
    '113': 17
    '114': 18
    '115': 19
    '116': 20
    '117': 21
    '118': 22
    '119': 23
    '12': 24
    '120': 25
    '121': 26
    '122': 27
    '123': 28
    '124': 29
    '125': 30
    '126': 31
    '127': 32
    '128': 33
    '129': 34
    '13': 35
    '130': 36
    '131': 37
    '132': 38
    '133': 39
    '134': 40
    '14': 41
    '15': 42
    '16': 43
    '17': 44
    '18': 45
    '19': 46
    '2': 47
    '20': 48
    '21': 49
    '22': 50
    '23': 51
    '24': 52
    '25': 53
    '26': 54
    '27': 55
    '28': 56
    '29': 57
    '3': 58
    '30': 59
    '31': 60
    '32': 61
    '33': 62
    '34': 63
    '35': 64
    '36': 65
    '37': 66
    '38': 67
    '39': 68
    '4': 69
    '40': 70
    '41': 71
    '42': 72
    '43': 73
    '44': 74
    '45': 75
    '46': 76
    '47': 77
    '48': 78
    '49': 79
    '5': 80
    '50': 81
    '51': 82
    '52': 83
    '53': 84
    '54': 85
    '55': 86
    '56': 87
    '57': 88
    '58': 89
    '59': 90
    '6': 91
    '60': 92
    '61': 93
    '62': 94
    '63': 95
    '64': 96
    '65': 97
    '66': 98
    '67': 99
    '68': 100
    '69': 101
    '7': 102
    '70': 103
    '71': 104
    '72': 105
    '73': 106
    '74': 107
    '75': 108
    '76': 109
    '77': 110
    '78': 111
    '79': 112
    '8': 113
    '80': 114
    '81': 115
    '82': 116
    '83': 117
    '84': 118
    '85': 119
    '86': 120
    '87': 121
    '88': 122
    '89': 123
    '9': 124
    '90': 125
    '91': 126
    '92': 127
    '93': 128
    '94': 129
    '95': 130
    '96': 131
    '97': 132
    '98': 133
    '99': 134
  season:
    autumn: 0
    spring: 1
    summer: 2
    winter: 3
embedding_paddings: []
embedding_sizes:
  is_ocean: !!python/tuple
  - 2
  - 1
  location_id: !!python/tuple
  - 135
  - 25
  season: !!python/tuple
  - 4
  - 3
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 128
learning_rate: 0.02
log_gradient_flow: false
log_interval: 1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 50
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 3
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups:
  - location_id
  method: standard
  missing_:
    center: 16.15167299129572
    scale: 4.923531714658623
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 135
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            +PQQI2mCLUDVa+suSYcuQJYhfHpQgS5AqkOn2GylLEBn+pXrm/wkQAvUKNiBzS5ACAvv3EhYMEBo
            qXkPmLEyQHGmX7nGOTNApVIO0+hSM0DCp4cYBx0zQMDQROoPEShAF42dEVOtK0DrLvF94VUvQGTg
            PxRnoCVA6fnmB5y8K0CwJjer8FYyQFlCf3nsKzNAiJHEEsZmM0BoWF0zbiwzQNEOgq7ayTFAeSrK
            fNpMJEBASm+0TIsmQFYNdQOZeCxANk2JCtQmMEDigiew6qsvQBQ93/zeezJAWoWSIu7mMkDnB/A6
            kGozQOnDfsqYvTJAfjYXIRcCMkA+WHjnnnklQIS736uwEilAvT1zLLR0MECJCkD5pkgxQH5sf15K
            tjBAaeyMuKFfMkBcXNVQeQkzQDqPPuzfaDNAl0nbhG89MkCF4z62iYsyQFhdMxi1NTFA1uRmFUiu
            MUD5NyTMBB0yQAslRbTpkDJAB1wLuZB8LUASt7iq8WMuQJjdCgoxiS9AcdzH9vsaL0B9DrgWUBYw
            QNK9ZdKCqjBA9dq6SzAkMUCPIzgJBJsxQNXXu6mfEzJAAOVLYX+YMkBhFwYZgH0tQPW/Bq03SS5A
            ZOA/FOuNLkCbi5Bm4zcwQKs1nqWivy9AQ91AcgxkMEB5e+ZYaI8wQJHfxpjiKjFA7XEEJxHfMUCO
            Fo2d5Z8yQLTvcKaHgC1AQgb+Q1E9LkAHrSeVygUsQJkgHrMcYCxA7QU0rHa+MECqXlt3mU8uQNMb
            LRqdfTBAMvAfigf9MEA1CnZhmMQxQFD0fPPHzTJATb9yfdaFLUDVoVNsslkuQMXB3e8lSyhAaD2p
            lKMyKUDNsRguvHIsQJSAoYn8PzFA0r1l0uD2MEBdhDRb5IMxQB1wLeT2ijJAtqv/NRgOM0Cc6Veu
            150tQNkZcYuDkC5AEQjVhos6JkDQAddCyqspQFnWrv6jsCtAI6TZkn4WMUD4RS3/+LMxQBvPUvMg
            WjFATjjuY+mUMkCgl90KrkgyQBjQsLqm0S1AT0WZz0nxLkCx1RrPHiMnQMxuBYWwzilAJtnjCEbX
            KkCtQkkR7TIwQBvPUvPk3DFAF42dEQsjMkDumWMxapoxQG8gOWdNBTJAxaYpUZn/LUB1VOUVxSgv
            QMkeR3DWUSlAdR592PefJ0Ch2vCzxSssQDCFrdYkyy9A2LupQ7G0MEAOP5uLPiExQMrNKpRonjJA
            2chUr9mvMkAm9Jen6uUtQI5M9dqeRC9A2pLscWT/KkA5TCtDNLMoQH29mzq8TClAfEQgVGcaLkAI
            JqN7kzIuQLKsXf0dSTJAMkE8ZuknM0Ds3dShJ4MtQGiOxXDNZixAcH4ArxOsLUAeBF1p6BwpQK14
            sU5OWC5AsFyf6IG2KEDHYrjg4akvQENJEe2KTzJAnsCa3GpJM0AtGjsjZAkzQLj7vUoqtypA/C5p
            wJCmBUBi3/E8pAIGQNQr8Z6qPgZAQOaqGHcVG0AOpWetvzMaQDeVad/e3B1AQCpui1icGECC7D3O
            DtAUQD9bfn10/xJAcjz620qOEUDnTAQsRhQbQBCXTQuaVxpAtN3WDCi2G0CeI75fgdsFQAPUkr3W
            dhpA4sHXbF/jGkDTLUhhqNYUQEdv9CZREBRAElH0suumEkDPV5YBUFEUQC9AKMH3qB9AktP/LAej
            GkCCiz+QZaMaQPwEs2DbnRlADHu29zaWBUAEfZgCNeUWQJfHkTsKUxRARq7CFpKSFEBblSBjgcAS
            QGGRcNq09hVAGUh9KWXiIED1GiUL6SQcQDn1/oHpYhtAEnUUvtl1FEBjfI+Yx0YTQMyEAXhBVQVA
            Po4VoWvwE0BAHD1MsrETQH9Q2QSA+xJAmTdU6VhgGEB9R5CV/ywhQIz+RdRh4ARAroBzea81BEDI
            9HU07KoDQDxhftCXKwNArkljwYCHBkA6EwY9Pm4GQOqWro7UCwZACMiRrVeKBUCGn46/Mh8FQEiX
            CXVC5wRAzmipIdeCBEACDQu01L0DQDgUF2RULwNAvDG3YoHRAkCikmhDtBcHQIZUEpz9uAZAuKfb
            XhCVBECkVDw9V+wFQOzlZPiFRQRAGPX7QoAFBEA8LIuQjAoEQOBEj+nGdgJAgHZpjEBBAkAQPT0h
            Y8ICQL7gifwT0gdADvwMkiOWB0A8/yMZZQgQQBun3f1MSBFA6tbGK5W0BUAkK4OTQCARQEqBCP3f
            FxRAEdIcwrTzEUDg+tNdxOUGQJBzDQu7LARAOgcPMP7SCEDcjxh28MsJQDKrubwK9hNAgq58ySdU
            GECVckTr5JoZQCwIaXrfFQVAzDWBsCuNGkDWmI6pSHgZQHa3FU4+ng1A0Eq4wPUrB0BKY1GvnkgK
            QJKlRWadJAtApeikQvO9FUASUD6gT6YbQHe7STeVYBxAe2VAzS6MHUBODTVSR5kEQOgy6Z2IrRtA
            uY7QP7MKFUAk/gFp+tgPQHo3n6mAFgxAej8j0n78DEB1PVdFYdQVQFvNqM1PnBxAdBrP6dvZHUCN
            yA2NTT0fQPpYkPSyEB5AKo/pTwgNBEBRcf6+jDQVQO/myRGjOhFAcFna4WRjDkB0EwyM6ekOQM0c
            py/tgRVAVrTe1/vLHEBYuPVkM/IeQCw8P/rRMCBA1ouzSUS6H0AfEQFbbHwVQODow7jaiwNAJeft
            K7iKEEDKwLrYyNoQQOrKEnTRtRBA65fDMqPAFUD2F4TnWKEcQOjURJ5SqB5AaGx9sVEfH0DBx/ve
            RuQcQGgzz8ZG1hNAVRMeHZP0EED2G0xpJg4GQC1Wc8IO+RZA3gUvrnIDF0Bim72dmBMZQObpGnOS
            jR1AOhHkXVSdHEB6hpNUu3sbQB4uShalZRdAAY17M2hOEUAQ1RYEpeEUQHJ/o1hF9BlA
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 135
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAH
              AAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAAAAAAAAsAAAAAAAAADAAAAAAAAAANAAAAAAAAAA4A
              AAAAAAAADwAAAAAAAAAQAAAAAAAAABEAAAAAAAAAEgAAAAAAAAATAAAAAAAAABQAAAAAAAAAFQAA
              AAAAAAAWAAAAAAAAABcAAAAAAAAAGAAAAAAAAAAZAAAAAAAAABoAAAAAAAAAGwAAAAAAAAAcAAAA
              AAAAAB0AAAAAAAAAHgAAAAAAAAAfAAAAAAAAACAAAAAAAAAAIQAAAAAAAAAiAAAAAAAAACMAAAAA
              AAAAJAAAAAAAAAAlAAAAAAAAACYAAAAAAAAAJwAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAAAAA
              AAArAAAAAAAAACwAAAAAAAAALQAAAAAAAAAuAAAAAAAAAC8AAAAAAAAAMAAAAAAAAAAxAAAAAAAA
              ADIAAAAAAAAAMwAAAAAAAAA0AAAAAAAAADUAAAAAAAAANgAAAAAAAAA3AAAAAAAAADgAAAAAAAAA
              OQAAAAAAAAA6AAAAAAAAADsAAAAAAAAAPAAAAAAAAAA9AAAAAAAAAD4AAAAAAAAAPwAAAAAAAABA
              AAAAAAAAAEEAAAAAAAAAQgAAAAAAAABDAAAAAAAAAEQAAAAAAAAARQAAAAAAAABGAAAAAAAAAEcA
              AAAAAAAASAAAAAAAAABJAAAAAAAAAEoAAAAAAAAASwAAAAAAAABMAAAAAAAAAE0AAAAAAAAATgAA
              AAAAAABPAAAAAAAAAFAAAAAAAAAAUQAAAAAAAABSAAAAAAAAAFMAAAAAAAAAVAAAAAAAAABVAAAA
              AAAAAFYAAAAAAAAAVwAAAAAAAABYAAAAAAAAAFkAAAAAAAAAWgAAAAAAAABbAAAAAAAAAFwAAAAA
              AAAAXQAAAAAAAABeAAAAAAAAAF8AAAAAAAAAYAAAAAAAAABhAAAAAAAAAGIAAAAAAAAAYwAAAAAA
              AABkAAAAAAAAAGUAAAAAAAAAZgAAAAAAAABnAAAAAAAAAGgAAAAAAAAAaQAAAAAAAABqAAAAAAAA
              AGsAAAAAAAAAbAAAAAAAAABtAAAAAAAAAG4AAAAAAAAAbwAAAAAAAABwAAAAAAAAAHEAAAAAAAAA
              cgAAAAAAAABzAAAAAAAAAHQAAAAAAAAAdQAAAAAAAAB2AAAAAAAAAHcAAAAAAAAAeAAAAAAAAAB5
              AAAAAAAAAHoAAAAAAAAAewAAAAAAAAB8AAAAAAAAAH0AAAAAAAAAfgAAAAAAAAB/AAAAAAAAAIAA
              AAAAAAAAgQAAAAAAAACCAAAAAAAAAIMAAAAAAAAAhAAAAAAAAACFAAAAAAAAAIYAAAAAAAAA
          name: location_id
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 2
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- is_ocean
- location_id
static_reals:
- lat
- lon
time_varying_categoricals_decoder:
- season
time_varying_categoricals_encoder:
- season
time_varying_reals_decoder:
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
time_varying_reals_encoder:
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
- 2t
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
weight_decay: 0.0
x_categoricals:
- is_ocean
- location_id
- season
x_reals:
- lat
- lon
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
- 2t
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
