attention_head_size: 2
categorical_groups: {}
causal_attention: true
dropout: 0.3
embedding_labels:
  is_ocean:
    land: 0
    ocean: 1
  location_id:
    '0': 0
    '1': 1
    '10': 2
    '100': 3
    '101': 4
    '102': 5
    '103': 6
    '104': 7
    '105': 8
    '106': 9
    '107': 10
    '108': 11
    '109': 12
    '11': 13
    '110': 14
    '111': 15
    '112': 16
    '113': 17
    '114': 18
    '115': 19
    '116': 20
    '117': 21
    '118': 22
    '119': 23
    '12': 24
    '120': 25
    '121': 26
    '122': 27
    '123': 28
    '124': 29
    '125': 30
    '126': 31
    '127': 32
    '128': 33
    '129': 34
    '13': 35
    '130': 36
    '131': 37
    '132': 38
    '133': 39
    '134': 40
    '14': 41
    '15': 42
    '16': 43
    '17': 44
    '18': 45
    '19': 46
    '2': 47
    '20': 48
    '21': 49
    '22': 50
    '23': 51
    '24': 52
    '25': 53
    '26': 54
    '27': 55
    '28': 56
    '29': 57
    '3': 58
    '30': 59
    '31': 60
    '32': 61
    '33': 62
    '34': 63
    '35': 64
    '36': 65
    '37': 66
    '38': 67
    '39': 68
    '4': 69
    '40': 70
    '41': 71
    '42': 72
    '43': 73
    '44': 74
    '45': 75
    '46': 76
    '47': 77
    '48': 78
    '49': 79
    '5': 80
    '50': 81
    '51': 82
    '52': 83
    '53': 84
    '54': 85
    '55': 86
    '56': 87
    '57': 88
    '58': 89
    '59': 90
    '6': 91
    '60': 92
    '61': 93
    '62': 94
    '63': 95
    '64': 96
    '65': 97
    '66': 98
    '67': 99
    '68': 100
    '69': 101
    '7': 102
    '70': 103
    '71': 104
    '72': 105
    '73': 106
    '74': 107
    '75': 108
    '76': 109
    '77': 110
    '78': 111
    '79': 112
    '8': 113
    '80': 114
    '81': 115
    '82': 116
    '83': 117
    '84': 118
    '85': 119
    '86': 120
    '87': 121
    '88': 122
    '89': 123
    '9': 124
    '90': 125
    '91': 126
    '92': 127
    '93': 128
    '94': 129
    '95': 130
    '96': 131
    '97': 132
    '98': 133
    '99': 134
  season:
    autumn: 0
    spring: 1
    summer: 2
    winter: 3
embedding_paddings: []
embedding_sizes:
  is_ocean: !!python/tuple
  - 2
  - 1
  location_id: !!python/tuple
  - 135
  - 25
  season: !!python/tuple
  - 4
  - 3
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 128
learning_rate: 0.02
log_gradient_flow: false
log_interval: 1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 50
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 3
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups:
  - location_id
  method: standard
  missing_:
    center: 16.492508199173592
    scale: 5.016372972129703
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 135
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            qmF2cDPBLUCCSOuFE8guQB4cQaTFxi5A/UnGoijpLUCVZ+Jj5ycmQNjmdBU3JTBA7rulEO3tMEB+
            txS6cSAzQO67pRBrlzNAct8tBZ+lM0Ca+LivYrkzQGji4z4HMylAp6s8E1/sLEBpvYDtoJ8vQFov
            YBuT1yZAEGm9gH8CLUBvKfSnOL4yQMsz8fFzjjNAG2YHR7K+M0ADtjldy5IzQF/ANifFhzJAV3km
            PotqJUCeiY/7e7AnQMXHfbfmnC1ASsaiGpVNMEBsc7qKvVIwQL9bCn1/3jJAUQ2zww9MM0BGNczO
            IcAzQCvPxMf/LjNAvYBtjuvQMkBuTld5KrsmQPFx3y19XypAWVTDbHTiMEC9gG1OkKkxQB/33dKb
            3DBADNjmdAG/MkBOV3kmpGMzQCgZiyoxvTNAue+WQve/MkBWnonPnlgzQGuYHRz+WzFAusozcT3V
            MUAM2OZ08UQyQLDN6arLuDJAQMlY1PDCLUAsqmH27awuQFd5Jj5hzy9Ana7yzP5kL0Dxcd+tezsw
            QOWZ+LgB0DBA5Zn4+EdLMUB4S6G/0sExQPFx3+2+OTJA2OZ0VWK/MkBEWi9gacctQGCb01WIky5A
            pPUCtp7PLkA3p6t8Xl0wQAZsczrLAzBAJWNRjamKMECgZCzqQLowQNRVnsnxTjFAS6E/CXQCMkDz
            THyc8sUyQHLfLYXS0y1Abk5X+U6OLkAHRxBpvpgsQK0XsM3UDy1AL2CbUyzmMECVZ+JjxQQvQDE7
            OAJs9DBA8JZC/xxoMUASRFrvGP4xQERaL2D8+DJAewHbHLnfLUBJ6wVsLbouQIfZwZEAGSlApPUC
            tj9LKkBKxqKatKItQKerPJPFZzFA80x83NKbMUBwBJEW/yUyQMIRRNpu4DJA6E8yFgpFM0CdrvJM
            sQAuQJr4uO+t+C5Ai2qYHdIlJ0DeUuhP6PAqQG8p9KcVBi1AtxT6U5bRMUD8bik0c9sxQAHbnG4O
            ETJAkPtuKYkbM0AcQaT1zaQyQNjmdJVVQi5AWVTDbE1lL0C9gG1OmwooQEY1zA7rHitA1FWeiYJE
            LEAf991SVvowQMh9t5RvpDJAWVTDrH9LMkDeUuhPwx0yQJvTVd7oajJAJWNRjZ2CLkBaL2Cb0qkv
            QEcQab1vMCpAmB0cwaTvKEB2cASRlqwtQBBpvUCqsjBAw+zgiH98MUBuTlf5nKIxQE5XeeYAxTJA
            bk5X+RQPM0CqYXZwSoUuQErGopon2y9Ac7rKMxniK0DoTzIWtwgqQP8kY1EwwipAIq0XsJaXL0CN
            RTXMiZgvQI4g0jpbvDJAkPtu6T6IM0D2Ara5csUtQCn0J5lAay1AnomPe6e2LkDawRHELSsqQIJI
            64Vbxi9A0noBW3cUKkBidnAEFX4wQF/ANqch1zJAZSyq4ZmdM0Di477bsn8zQFd5Jr6G2StAlkFs
            5xJBBkC0y1XplpYGQDTsRE9nzwZA4IBqPtQZG0CkiF9vvGkaQLFkpDHv8B1AyIbPUpK+GEBNREnU
            4CAVQAlRmXvDWhNAjJdOxs7jEUCYBqC7akQbQAM9XIgAeBpAmnA1c7TIG0AMny7DPlQGQJLjs2sA
            nxpAA58+ia0WG0CQNGZHPDoVQHNFoqT7cBRAkm1lzBsGE0BjaWSFxaEUQFM9I0IR6R9A6/Rt4s3P
            GkD92Cj4MtgaQNFQIcRc3RlAik2cA+/1BUCwrtemRjgXQBqrccmwtBRAdfkKTCDxFEAP1IABTCAT
            QHnkd8FcSBZAHa5TECwGIUCwo5eV1jUcQOgCD5Q6eRtAqAp6IlOyFEDWYAz30JsTQPilC00isQVA
            meb812BRFEArBLvtqhcUQAG+u9OhXBNA2cVgZ+61GEBeB7Jp61chQETKVDmPMgVAolDP5T5uBECa
            I+Rt780DQJr5O61FNgNAMMsihG8ZB0De+B5mOPsGQK6XRUyoiwZAjJ9kiQP9BUB8Mob004EFQL7V
            rEr8NwVAwlcNTWXBBEBUs4LfcOgDQHxDOHFkVANAmPtLXjPnAkDWRcKX2KgHQApbHz+pRQdAOK9A
            Cjn5BEA4YwL1x1oGQAz/CxMyiwRAVF5+SKozBECYdYHxOCMEQBT47h66igJASClWXHhWAkDm02Mf
            iNUCQBw5xOUlWwhABoKX+9ojCEBiCt3eny0QQIpXlLQbYxFAHiCAUyQMBkCnWckfkTMRQBPDRyAn
            IhRAEVr2+CL1EUC24V1AtvwGQOZXXB48TgRA8j4+79FYCUCsUi3HAVQKQJhpi/juHBRAVUqAN292
            GEDNQHTy8cIZQFbROEYkYgVAgWNx0JixGkCVVWZG7IgZQGKSbpPvyQ1AmDVkjmBtB0CsYi/BSMkK
            QNzM302JswtAXhl+D6vvFUDrfxfNBtMbQHGPItVAlxxA4TojffqyHUCmVarsE9oEQC4wXYjNsBtA
            AakqXL0LFUCpCnlPWAIQQPAWOK+YlAxA4IG/mUaKDUCsi+sKpRAWQFEmThbCyhxAe3n0EmsPHkAh
            ScMmEWMfQKbOjBECFx5AoqhWS301BECU0n1TCVMVQB5jR8jXYxFAorDLTTnjDkAmmYkNG3kPQCuN
            7qaEtBVABvGz5KsPHUC/32I2/CQfQAv6wIoUSCBAB9cB6k3rH0AlMTTXuq0VQGLxD+YvpANAc2fo
            kI+9EEARdgMLsg0RQA35U64V9BBA3VPy+a78FUCNTUHkh90cQEZ6bJ0+5x5AUR3PUAtfH0DhkeTR
            nhQdQHFXjxPEEBRA9/IfFqUnEUAut6KFwaAGQI1sVVlkBhdATYhSQyYIF0Bw4pCNtVIZQLvpfeg+
            tx1A42YcLErJHECUnoMyH6EbQGzUfM/zohdARnXJSW+sEUDvzjlpZxEVQBcG7KsADhpA
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 135
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAH
              AAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAAAAAAAAsAAAAAAAAADAAAAAAAAAANAAAAAAAAAA4A
              AAAAAAAADwAAAAAAAAAQAAAAAAAAABEAAAAAAAAAEgAAAAAAAAATAAAAAAAAABQAAAAAAAAAFQAA
              AAAAAAAWAAAAAAAAABcAAAAAAAAAGAAAAAAAAAAZAAAAAAAAABoAAAAAAAAAGwAAAAAAAAAcAAAA
              AAAAAB0AAAAAAAAAHgAAAAAAAAAfAAAAAAAAACAAAAAAAAAAIQAAAAAAAAAiAAAAAAAAACMAAAAA
              AAAAJAAAAAAAAAAlAAAAAAAAACYAAAAAAAAAJwAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAAAAA
              AAArAAAAAAAAACwAAAAAAAAALQAAAAAAAAAuAAAAAAAAAC8AAAAAAAAAMAAAAAAAAAAxAAAAAAAA
              ADIAAAAAAAAAMwAAAAAAAAA0AAAAAAAAADUAAAAAAAAANgAAAAAAAAA3AAAAAAAAADgAAAAAAAAA
              OQAAAAAAAAA6AAAAAAAAADsAAAAAAAAAPAAAAAAAAAA9AAAAAAAAAD4AAAAAAAAAPwAAAAAAAABA
              AAAAAAAAAEEAAAAAAAAAQgAAAAAAAABDAAAAAAAAAEQAAAAAAAAARQAAAAAAAABGAAAAAAAAAEcA
              AAAAAAAASAAAAAAAAABJAAAAAAAAAEoAAAAAAAAASwAAAAAAAABMAAAAAAAAAE0AAAAAAAAATgAA
              AAAAAABPAAAAAAAAAFAAAAAAAAAAUQAAAAAAAABSAAAAAAAAAFMAAAAAAAAAVAAAAAAAAABVAAAA
              AAAAAFYAAAAAAAAAVwAAAAAAAABYAAAAAAAAAFkAAAAAAAAAWgAAAAAAAABbAAAAAAAAAFwAAAAA
              AAAAXQAAAAAAAABeAAAAAAAAAF8AAAAAAAAAYAAAAAAAAABhAAAAAAAAAGIAAAAAAAAAYwAAAAAA
              AABkAAAAAAAAAGUAAAAAAAAAZgAAAAAAAABnAAAAAAAAAGgAAAAAAAAAaQAAAAAAAABqAAAAAAAA
              AGsAAAAAAAAAbAAAAAAAAABtAAAAAAAAAG4AAAAAAAAAbwAAAAAAAABwAAAAAAAAAHEAAAAAAAAA
              cgAAAAAAAABzAAAAAAAAAHQAAAAAAAAAdQAAAAAAAAB2AAAAAAAAAHcAAAAAAAAAeAAAAAAAAAB5
              AAAAAAAAAHoAAAAAAAAAewAAAAAAAAB8AAAAAAAAAH0AAAAAAAAAfgAAAAAAAAB/AAAAAAAAAIAA
              AAAAAAAAgQAAAAAAAACCAAAAAAAAAIMAAAAAAAAAhAAAAAAAAACFAAAAAAAAAIYAAAAAAAAA
          name: location_id
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 2
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- is_ocean
- location_id
static_reals:
- lat
- lon
time_varying_categoricals_decoder:
- season
time_varying_categoricals_encoder:
- season
time_varying_reals_decoder:
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
time_varying_reals_encoder:
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
- 2t
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
weight_decay: 0.0
x_categoricals:
- is_ocean
- location_id
- season
x_reals:
- lat
- lon
- time_idx_norm
- year
- dayofyear_sin
- dayofyear_cos
- month_sin
- month_cos
- 2t
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
